blank_issues_enabled: false
contact_links:
  - name: kendryte Official Website
    about: kendryte 官方网站
    url: https://canaan-creative.com/product/%E5%8B%98%E6%99%BAk510
  - name: kendryte Community
    about: kendryte 开发者社区
    url: https://canaan-creative.com/developer
  - name: K510 CRB-KIT Link  
    about: K510 CRB-KIT 购买链接
    url: https://item.taobao.com/item.htm?spm=a230r.1.14.1.22714815bDh5ei&id=673510674381&ns=1&abbucket=0&mt=
